services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: user_password
      MARIADB_ROOT_PASSWORD: root_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
  
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend


networks:
  backend:
    driver: bridge


volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb