server {
    listen 80;
    server_name cloud1.com;

    location / {
        proxy_pass http://wordpress;

        # For backend
        proxy_set_header Host $host; # Passes original Host header
        proxy_set_header X-Real-IP $remote_addr; # Passes real client IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Tracks proxy chain
        proxy_set_header X-Forwarded-Proto $scheme; # Passes http or https protocol
    }
}

server {
    listen 80;
    server_name pma.cloud1.com;

    location / {
        proxy_pass http://phpmyadmin;

        # For backend
        proxy_set_header Host $host; # Passes original Host header
        proxy_set_header X-Real-IP $remote_addr; # Passes real client IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Tracks proxy chain
        proxy_set_header X-Forwarded-Proto $scheme; # Passes http or https protocol
    }
}

# server {
#     listen 443 ssl;

#     server_name cloud1.com;

#     ssl on;
#     ssl_certificate cert;
#     ssl_certificate_key cert.key;

#     location / {
#         proxy_pass http://wordpress;

#         # For backend
#         proxy_set_header Host $host; # Passes original Host header
#         proxy_set_header X-Real-IP $remote_addr; # Passes real client IP
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Tracks proxy chain
#         proxy_set_header X-Forwarded-Proto $scheme; # Passes http or https protocol
#     }
# }

# TODO: enable this after testing
# server {
#     listen 80 default_server;
#     server_name _;
    
#     return 444;
# }

